name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: get
      run: go get ./...

    - name: vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -v .
